# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1162257564);
user_pref("app.update.lastUpdateTime.background-update-timer", 1162257541);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1162257564);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1229721048);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1252507997);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1162257568);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://www.sabayonlinux.org");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.2");
user_pref("extensions.enabledItems", "langpack-af@firefox.mozilla.org:3.5.2,langpack-eu@firefox.mozilla.org:3.5.2,langpack-ca@firefox.mozilla.org:3.5.2,langpack-cy@firefox.mozilla.org:3.5.2,langpack-cs@firefox.mozilla.org:3.5.2,langpack-da@firefox.mozilla.org:3.5.2,langpack-de@firefox.mozilla.org:3.5.2,langpack-es-ES@firefox.mozilla.org:3.5.2,langpack-eo@firefox.mozilla.org:3.5.2,langpack-et@firefox.mozilla.org:3.5.2,langpack-fr@firefox.mozilla.org:3.5.2,langpack-gl@firefox.mozilla.org:3.5.2,langpack-el@firefox.mozilla.org:3.5.2,langpack-gu-IN@firefox.mozilla.org:3.5.2,langpack-he@firefox.mozilla.org:3.5.2,langpack-hi-IN@firefox.mozilla.org:3.5.2,langpack-is@firefox.mozilla.org:3.5.2,langpack-it@firefox.mozilla.org:3.5.2,langpack-ja@firefox.mozilla.org:3.5.2,langpack-ko@firefox.mozilla.org:3.5.2,langpack-lv@firefox.mozilla.org:3.5.2,langpack-lt@firefox.mozilla.org:3.5.2,langpack-hu@firefox.mozilla.org:3.5.2,langpack-mn@firefox.mozilla.org:3.5.2,langpack-nl@firefox.mozilla.org:3.5.2,langpack-pa-IN@firefox.mozilla.org:3.5.2,langpack-ro@firefox.mozilla.org:3.5.2,langpack-ru@firefox.mozilla.org:3.5.2,langpack-sk@firefox.mozilla.org:3.5.2,langpack-sl@firefox.mozilla.org:3.5.2,langpack-fi@firefox.mozilla.org:3.5.2,langpack-sv-SE@firefox.mozilla.org:3.5.2,langpack-tr@firefox.mozilla.org:3.5.2,langpack-uk@firefox.mozilla.org:3.5.2,langpack-bg@firefox.mozilla.org:3.5.2,langpack-mk@firefox.mozilla.org:3.5.2,langpack-sr@firefox.mozilla.org:3.5.2,langpack-ar@firefox.mozilla.org:3.5.2,langpack-bn-BD@firefox.mozilla.org:3.5.2,langpack-fa@firefox.mozilla.org:3.5.2,langpack-hr@firefox.mozilla.org:3.5.2,langpack-kk@firefox.mozilla.org:3.5.2,langpack-ta@firefox.mozilla.org:3.5.2,langpack-vi@firefox.mozilla.org:3.5.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.2");
user_pref("extensions.lastAppVersion", "3.5.2");
user_pref("extensions.update.notifyUser", false);
user_pref("general.useragent.locale", "en-US");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", true);
user_pref("privacy.cpd.downloads", true);
user_pref("privacy.cpd.formdata", true);
user_pref("privacy.cpd.history", true);
user_pref("privacy.cpd.offlineApps", false);
user_pref("privacy.cpd.passwords", false);
user_pref("privacy.cpd.sessions", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.item.offlineApps", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/getkey?client=Firefox2.0&", 1163714745);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1255099989);
user_pref("urlclassifier.tableversion.goog-black-url", "1.7079");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.17");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
